project:
  type: website

website:
  title: "isss608-jan2526"
  navbar:
    right: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    left:
      - text: Hands-on Exercise
        menu: 
          - href: Hands-on_Ex/Hands-on_ex01/handson_ex1.html
            text: Hands-on Exercise 1  
      - text: In-class Exercise
        menu: 
          - text: In-class Exercise 1
      - text: Take-home Exercise
        menu: 
          - text: Take-home Exercise 1

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

